import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "@/Components/Provider/AuthProvider/AuthProvider";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import { Suspense } from "react";
 
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Auraloom",
  description: "Generated by Team HexaDevs",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        {/* <Suspense fallback={<div>Loading podcasts...</div>}> */}
            <Navbar />
        {/* </Suspense> */}
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
