"use client";
import Head from "next/head";
import Image from "next/image";
import img from "../../../public/idea2.gif";

export default function IdeaGeneration() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <Head>
        <title>Generate a Response</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative w-full h-screen flex items-center justify-center">
        {/* Background Image */}
        <div className="absolute inset-0 w-full h-full">
          <Image
            src={img}
            alt="Background Idea"
            layout="fill"
            objectFit="cover"
            quality={100}
            className="w-full h-96"
          />
        </div>

        {/* Main Content */}
        <div className="absolute bottom-28 transform translate-y-1/2 w-full flex flex-col items-center justify-center text-center z-10">
          <div className="flex flex-col sm:flex-row items-center space-y-4 sm:space-y-0 sm:space-x-4">
            {/* Input Field */}
            <input
              type="text"
              placeholder="What research methods were used in..."
              className="px-4 py-2 w-full sm:w-96 border border-gray-300 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-400"
            />

            {/* Generate Button */}
            <button className="px-6 py-2 w-full sm:w-auto bg-blue-500 text-white font-bold rounded-full hover:bg-blue-600 transition duration-300">
              Generate
            </button>
          </div>

          <div className="mt-4">
            <a href="#" className="text-white hover:underline">
              {/* Show other categories */}
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}
